# Emits wff/src/main/res/raw/watchface.xml (Watch Face Format v1).
# Geometry mirrors app/.../WatchFaceService.kt's Canvas renderer on a 450x450 canvas
# (cx=cy=225, r=180). The 96 tick marks are unrolled because WFF has no repeat.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\make-watchface.ps1
#
# Things this runtime (Galaxy Watch 7, Wear OS 6) taught us the hard way:
#   - <DigitalClock>/<TimeText> DOES NOT RENDER. Silently. No log line, no parse error, the
#     element is simply absent from the face. Tried hh:mm, h:mm a and HH:mm, with and
#     without hourFormat. A <PartText> whose <Template> reads [HOUR_1_12] / [MINUTE]
#     renders fine, so every clock-ish string here is built that way. Do not "simplify"
#     these back to DigitalClock.
#   - DefaultProviderPolicy uses primaryProviderType, NOT primaryProviderDefaultType; the
#     wrong name makes the runtime throw "primaryDataSourceDefaultType EMPTY must be in the
#     supportedTypes list" and the face cannot be added as a favourite.
#   - Rotate a hand with a full-size <Group pivotX="0.5" pivotY="0.5"> + Transform angle;
#     a Transform on a narrow PartDraw did not render.
#   - Complication expressions ([COMPLICATION.*]) only resolve INSIDE that slot's
#     <Complication> block, so nothing outside a slot can be styled from phone data. That
#     is why the ring/ticks/hand are amber in both count modes while the centre figure
#     switches colour: the figure lives inside slot 1, they do not.
$out = Join-Path $PSScriptRoot '..\wff\src\main\res\raw\watchface.xml'
$inv = [System.Globalization.CultureInfo]::InvariantCulture
function F([double]$v) { $v.ToString('0.##', $inv) }

$cx = 225.0; $cy = 225.0; $r = 180.0
$minuteOfDay = '([HOUR_0_23] * 60 + [MINUTE])'
$dayAngle    = "($minuteOfDay / 1440) * 360"

$AMBER = '#FFF59E0B'; $CYAN = '#FF38BDF8'; $L2 = '#FF94A3B8'; $L3 = '#FF64748B'

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
[void]$sb.AppendLine('<!--')
[void]$sb.AppendLine('  1440 Planner - Watch Face Format v1 face. GENERATED by tools/make-watchface.ps1')
[void]$sb.AppendLine('  (the 96 tick marks are unrolled); edit the generator, not this file.')
[void]$sb.AppendLine('  Ring, ticks, 24h sweep, minute hand, the centre figure and the clock are all computed')
[void]$sb.AppendLine('  from the WATCH clock and need no phone data. Slots 1 and 3 hold the two count-mode')
[void]$sb.AppendLine('  variants of that figure and gate each other (only the active mode has data, so only')
[void]$sb.AppendLine('  one renders); slot 2 carries the current or next block.')
[void]$sb.AppendLine('  Per-block arcs are still not drawable here; see docs/STATUS.md.')
[void]$sb.AppendLine('-->')
[void]$sb.AppendLine('<WatchFace width="450" height="450" clipShape="CIRCLE">')
[void]$sb.AppendLine('    <Metadata key="CLOCK_TYPE" value="ANALOG" />')
[void]$sb.AppendLine('    <Metadata key="PREVIEW_TIME" value="10:08:32" />')
[void]$sb.AppendLine('    <Scene backgroundColor="#FF07090F">')

# Outer ring
$rr = $r + $r * 0.125
[void]$sb.AppendLine('        <PartDraw x="0" y="0" width="450" height="450">')
[void]$sb.AppendLine("            <Ellipse x=`"$(F ($cx - $rr))`" y=`"$(F ($cy - $rr))`" width=`"$(F (2 * $rr))`" height=`"$(F (2 * $rr))`">")
[void]$sb.AppendLine('                <Stroke color="#8CF59E0B" width="1.5" />')
[void]$sb.AppendLine('            </Ellipse>')
[void]$sb.AppendLine('        </PartDraw>')

# 96 ticks
[void]$sb.AppendLine('        <PartDraw x="0" y="0" width="450" height="450">')
for ($i = 0; $i -lt 96; $i++) {
  $angle = ($i / 96.0) * 360.0 - 90.0
  $rad = $angle * [Math]::PI / 180.0
  $major = ($i % 4) -eq 0
  $inner = if ($major) { $r - $r * 0.06 } else { $r + $r * 0.01 }
  $outer = $r + $r * 0.06
  $x1 = $cx + $inner * [Math]::Cos($rad); $y1 = $cy + $inner * [Math]::Sin($rad)
  $x2 = $cx + $outer * [Math]::Cos($rad); $y2 = $cy + $outer * [Math]::Sin($rad)
  $color = if ($major) { '#E6F59E0B' } else { '#B43D4F66' }
  $width = if ($major) { '1.8' } else { '0.6' }
  [void]$sb.AppendLine("            <Line startX=`"$(F $x1)`" startY=`"$(F $y1)`" endX=`"$(F $x2)`" endY=`"$(F $y2)`">")
  [void]$sb.AppendLine("                <Stroke color=`"$color`" width=`"$width`" />")
  [void]$sb.AppendLine('            </Line>')
}
[void]$sb.AppendLine('        </PartDraw>')

# 24h progress sweep (0 deg = 12 o'clock in WFF, clockwise)
$arcR2 = $r - $r * 0.1
[void]$sb.AppendLine('        <PartDraw x="0" y="0" width="450" height="450">')
[void]$sb.AppendLine("            <Arc centerX=`"$(F $cx)`" centerY=`"$(F $cy)`" width=`"$(F (2 * $arcR2))`" height=`"$(F (2 * $arcR2))`" startAngle=`"0`" endAngle=`"0`" direction=`"CLOCKWISE`">")
[void]$sb.AppendLine("                <Transform target=`"endAngle`" value=`"$dayAngle`" />")
[void]$sb.AppendLine('                <Stroke color="#E6F59E0B" width="2.8" cap="ROUND" />')
[void]$sb.AppendLine('            </Arc>')
[void]$sb.AppendLine('        </PartDraw>')

# Minute hand on the 1440 dial: a full-size group rotated about the face centre.
# Drawn BEFORE the centre dial so the dial's opaque fill hides its inner half and the hand
# reads as a pointer on the ring instead of a line struck through the figure.
$handLen = $r * 0.86
[void]$sb.AppendLine('        <Group x="0" y="0" width="450" height="450" pivotX="0.5" pivotY="0.5" angle="0">')
[void]$sb.AppendLine("            <Transform target=`"angle`" value=`"$dayAngle`" />")
[void]$sb.AppendLine('            <PartDraw x="0" y="0" width="450" height="450">')
[void]$sb.AppendLine("                <Line startX=`"$(F $cx)`" startY=`"$(F $cy)`" endX=`"$(F $cx)`" endY=`"$(F ($cy - $handLen))`">")
[void]$sb.AppendLine('                    <Stroke color="#FFF59E0B" width="2.2" cap="ROUND" />')
[void]$sb.AppendLine('                </Line>')
[void]$sb.AppendLine('            </PartDraw>')
[void]$sb.AppendLine('        </Group>')

# Centre dial
$dialR = $r * 0.41
[void]$sb.AppendLine('        <PartDraw x="0" y="0" width="450" height="450">')
[void]$sb.AppendLine("            <Ellipse x=`"$(F ($cx - $dialR))`" y=`"$(F ($cy - $dialR))`" width=`"$(F (2 * $dialR))`" height=`"$(F (2 * $dialR))`">")
[void]$sb.AppendLine('                <Fill color="#FF07090F" />')
[void]$sb.AppendLine('                <Stroke color="#FF1F2D42" width="1" />')
[void]$sb.AppendLine('            </Ellipse>')
[void]$sb.AppendLine('        </PartDraw>')

# Slots 1 and 3: the headline figure, computed here from the WATCH clock so it ticks every
# minute by itself. It used to be a number the phone's complication sent, which meant it was
# only as fresh as the last complication update — and UPDATE_PERIOD_SECONDS never fires on
# this hardware (clamped to ~300 s), so with the phone app closed it could sit five minutes
# behind.
#
# The two slots occupy the SAME box and their data sources gate each other: CountUp returns
# data only while the phone counts up, CountDown only while it counts down, and a
# <Complication> block does not render when its slot is EMPTY. So exactly one figure is ever
# visible, and each carries its own accent colour. This roundabout arrangement exists because
# phone data cannot be read as a number here at all — see ComplicationHelper.kt.
$modes = @(
  @{ slot = 1; svc = 'CountUpComplicationService';   expr = $minuteOfDay;            color = $AMBER; name = 'Count up (elapsed)'   },
  @{ slot = 3; svc = 'CountDownComplicationService'; expr = "(1440 - $minuteOfDay)"; color = $CYAN;  name = 'Count down (remaining)' }
)
foreach ($m in $modes) {
  [void]$sb.AppendLine("        <ComplicationSlot slotId=`"$($m.slot)`" x=`"150`" y=`"158`" width=`"150`" height=`"68`" displayName=`"$($m.name)`" supportedTypes=`"SHORT_TEXT`" isCustomizable=`"FALSE`">")
  [void]$sb.AppendLine('            <BoundingOval x="0" y="0" width="150" height="68" />')
  [void]$sb.AppendLine("            <DefaultProviderPolicy primaryProvider=`"com.planner1440.app/com.planner1440.watchface.$($m.svc)`" primaryProviderType=`"SHORT_TEXT`" />")
  [void]$sb.AppendLine('            <Complication type="SHORT_TEXT">')
  [void]$sb.AppendLine('                <PartText x="0" y="0" width="150" height="46">')
  [void]$sb.AppendLine('                    <Text align="CENTER">')
  [void]$sb.AppendLine("                        <Font family=`"SYNC_TO_DEVICE`" size=`"38`" weight=`"BOLD`" color=`"$($m.color)`">")
  [void]$sb.AppendLine("                            <Template>%d<Parameter expression=`"$($m.expr)`" /></Template>")
  [void]$sb.AppendLine('                        </Font>')
  [void]$sb.AppendLine('                    </Text>')
  [void]$sb.AppendLine('                </PartText>')
  [void]$sb.AppendLine('                <PartText x="0" y="46" width="150" height="22">')
  [void]$sb.AppendLine('                    <Text align="CENTER">')
  [void]$sb.AppendLine("                        <Font family=`"SYNC_TO_DEVICE`" size=`"13`" color=`"$L3`">")
  [void]$sb.AppendLine('                            <Template>%s<Parameter expression="[COMPLICATION.TITLE]" /></Template>')
  [void]$sb.AppendLine('                        </Font>')
  [void]$sb.AppendLine('                    </Text>')
  [void]$sb.AppendLine('                </PartText>')
  [void]$sb.AppendLine('            </Complication>')
  [void]$sb.AppendLine('        </ComplicationSlot>')
}

# Wall clock, built from time expressions (see the DigitalClock note at the top).
# Right-aligned time + left-aligned meridiem so the pair stays centred without measuring
# text; AM/PM is two stacked labels picked by [AMPM_STATE] (0 = AM, 1 = PM).
[void]$sb.AppendLine('        <PartText x="97" y="228" width="135" height="30">')
[void]$sb.AppendLine('            <Text align="RIGHT">')
[void]$sb.AppendLine("                <Font family=`"SYNC_TO_DEVICE`" size=`"22`" color=`"$L2`">")
[void]$sb.AppendLine('                    <Template>%d:%02d<Parameter expression="[HOUR_1_12]" /><Parameter expression="[MINUTE]" /></Template>')
[void]$sb.AppendLine('                </Font>')
[void]$sb.AppendLine('            </Text>')
[void]$sb.AppendLine('        </PartText>')
foreach ($ap in @(
    @{ label = 'AM'; alpha = '255 * (1 - [AMPM_STATE])' },
    @{ label = 'PM'; alpha = '255 * [AMPM_STATE]' })) {
  [void]$sb.AppendLine('        <PartText x="236" y="236" width="60" height="22" alpha="255">')
  [void]$sb.AppendLine("            <Transform target=`"alpha`" value=`"$($ap.alpha)`" />")
  [void]$sb.AppendLine('            <Text align="LEFT">')
  [void]$sb.AppendLine("                <Font family=`"SYNC_TO_DEVICE`" size=`"13`" color=`"$L3`">")
  [void]$sb.AppendLine("                    <Template>$($ap.label)</Template>")
  [void]$sb.AppendLine('                </Font>')
  [void]$sb.AppendLine('            </Text>')
  [void]$sb.AppendLine('        </PartText>')
}

# Slot 2: current block if one is running, else the next one. Two lines: title, then the
# time qualifier ("till 9:45 PM" / "8:00 PM").
[void]$sb.AppendLine('        <ComplicationSlot slotId="2" x="75" y="306" width="300" height="54" displayName="Current or next block" supportedTypes="SHORT_TEXT" isCustomizable="TRUE">')
[void]$sb.AppendLine('            <BoundingOval x="0" y="0" width="300" height="54" />')
[void]$sb.AppendLine('            <DefaultProviderPolicy primaryProvider="com.planner1440.app/com.planner1440.watchface.NextBlockComplicationService" primaryProviderType="SHORT_TEXT" defaultSystemProvider="DATE" defaultSystemProviderType="SHORT_TEXT" />')
[void]$sb.AppendLine('            <Complication type="SHORT_TEXT">')
[void]$sb.AppendLine('                <PartText x="0" y="0" width="300" height="30">')
[void]$sb.AppendLine('                    <Text align="CENTER" ellipsis="TRUE">')
[void]$sb.AppendLine('                        <Font family="SYNC_TO_DEVICE" size="21" color="#FFE2E8F0">')
[void]$sb.AppendLine('                            <Template>%s<Parameter expression="[COMPLICATION.TEXT]" /></Template>')
[void]$sb.AppendLine('                        </Font>')
[void]$sb.AppendLine('                    </Text>')
[void]$sb.AppendLine('                </PartText>')
[void]$sb.AppendLine('                <PartText x="0" y="30" width="300" height="24">')
[void]$sb.AppendLine('                    <Text align="CENTER" ellipsis="TRUE">')
[void]$sb.AppendLine("                        <Font family=`"SYNC_TO_DEVICE`" size=`"15`" color=`"$L3`">")
[void]$sb.AppendLine('                            <Template>%s<Parameter expression="[COMPLICATION.TITLE]" /></Template>')
[void]$sb.AppendLine('                        </Font>')
[void]$sb.AppendLine('                    </Text>')
[void]$sb.AppendLine('                </PartText>')
[void]$sb.AppendLine('            </Complication>')
[void]$sb.AppendLine('        </ComplicationSlot>')

[void]$sb.AppendLine('    </Scene>')
[void]$sb.AppendLine('</WatchFace>')

$out = [System.IO.Path]::GetFullPath($out)
[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Output "wrote $out ($($sb.Length) chars)"
