# Emits wff/src/main/res/raw/watchface.xml (Watch Face Format v1).
# Geometry mirrors app/.../WatchFaceService.kt's Canvas renderer on a 450x450 canvas
# (cx=cy=225, r=180). The 96 tick marks are unrolled because WFF has no repeat.
#
#   powershell -NoProfile -ExecutionPolicy Bypass -File tools\make-watchface.ps1
#
# Attribute names that bit us on-device (Galaxy Watch 7, Wear OS 6):
#   - DefaultProviderPolicy uses primaryProviderType, NOT primaryProviderDefaultType; the
#     wrong name makes the runtime throw "primaryDataSourceDefaultType EMPTY must be in the
#     supportedTypes list" and the face cannot be added as a favourite.
#   - Rotate a hand with a full-size <Group pivotX="0.5" pivotY="0.5"> + Transform angle;
#     a Transform on a narrow PartDraw did not render.
$out = Join-Path $PSScriptRoot '..\wff\src\main\res\raw\watchface.xml'
$inv = [System.Globalization.CultureInfo]::InvariantCulture
function F([double]$v) { $v.ToString('0.##', $inv) }

$cx = 225.0; $cy = 225.0; $r = 180.0
$minuteOfDay = '([HOUR_0_23] * 60 + [MINUTE])'
$dayAngle    = "($minuteOfDay / 1440) * 360"

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
[void]$sb.AppendLine('<!--')
[void]$sb.AppendLine('  1440 Planner - Watch Face Format v1 face. GENERATED by tools/make-watchface.ps1')
[void]$sb.AppendLine('  (the 96 tick marks are unrolled); edit the generator, not this file.')
[void]$sb.AppendLine('  Clock-driven parts (ring, ticks, 24h progress sweep, minute hand, time) need no data.')
[void]$sb.AppendLine('  Slot 1 = minute counter, slot 2 = next block: both default to the complication data')
[void]$sb.AppendLine('  sources in the com.planner1440.app watch APK, which is where the phone snapshot lands.')
[void]$sb.AppendLine('  Per-block arcs are not drawable from a JSON snapshot in WFF; see docs/STATUS.md.')
[void]$sb.AppendLine('-->')
[void]$sb.AppendLine('<WatchFace width="450" height="450" clipShape="CIRCLE">')
[void]$sb.AppendLine('    <Metadata key="CLOCK_TYPE" value="ANALOG" />')
[void]$sb.AppendLine('    <Metadata key="PREVIEW_TIME" value="10:08:32" />')
[void]$sb.AppendLine('    <Scene backgroundColor="#FF07090F">')

# Outer ring
$rr = $r + $r * 0.125
[void]$sb.AppendLine('        <PartDraw x="0" y="0" width="450" height="450">')
[void]$sb.AppendLine("            <Ellipse x=`"$(F ($cx - $rr))`" y=`"$(F ($cy - $rr))`" width=`"$(F (2 * $rr))`" height=`"$(F (2 * $rr))`">")
[void]$sb.AppendLine('                <Stroke color="#8CF59E0B" width="1.5" />')
[void]$sb.AppendLine('            </Ellipse>')
[void]$sb.AppendLine('        </PartDraw>')

# 96 ticks
[void]$sb.AppendLine('        <PartDraw x="0" y="0" width="450" height="450">')
for ($i = 0; $i -lt 96; $i++) {
  $angle = ($i / 96.0) * 360.0 - 90.0
  $rad = $angle * [Math]::PI / 180.0
  $major = ($i % 4) -eq 0
  $inner = if ($major) { $r - $r * 0.06 } else { $r + $r * 0.01 }
  $outer = $r + $r * 0.06
  $x1 = $cx + $inner * [Math]::Cos($rad); $y1 = $cy + $inner * [Math]::Sin($rad)
  $x2 = $cx + $outer * [Math]::Cos($rad); $y2 = $cy + $outer * [Math]::Sin($rad)
  $color = if ($major) { '#E6F59E0B' } else { '#B43D4F66' }
  $width = if ($major) { '1.8' } else { '0.6' }
  [void]$sb.AppendLine("            <Line startX=`"$(F $x1)`" startY=`"$(F $y1)`" endX=`"$(F $x2)`" endY=`"$(F $y2)`">")
  [void]$sb.AppendLine("                <Stroke color=`"$color`" width=`"$width`" />")
  [void]$sb.AppendLine('            </Line>')
}
[void]$sb.AppendLine('        </PartDraw>')

# 24h progress sweep (0 deg = 12 o'clock in WFF, clockwise)
$arcR2 = $r - $r * 0.1
[void]$sb.AppendLine('        <PartDraw x="0" y="0" width="450" height="450">')
[void]$sb.AppendLine("            <Arc centerX=`"$(F $cx)`" centerY=`"$(F $cy)`" width=`"$(F (2 * $arcR2))`" height=`"$(F (2 * $arcR2))`" startAngle=`"0`" endAngle=`"0`" direction=`"CLOCKWISE`">")
[void]$sb.AppendLine("                <Transform target=`"endAngle`" value=`"$dayAngle`" />")
[void]$sb.AppendLine('                <Stroke color="#E6F59E0B" width="2.8" cap="ROUND" />')
[void]$sb.AppendLine('            </Arc>')
[void]$sb.AppendLine('        </PartDraw>')

# Centre dial
$dialR = $r * 0.41
[void]$sb.AppendLine('        <PartDraw x="0" y="0" width="450" height="450">')
[void]$sb.AppendLine("            <Ellipse x=`"$(F ($cx - $dialR))`" y=`"$(F ($cy - $dialR))`" width=`"$(F (2 * $dialR))`" height=`"$(F (2 * $dialR))`">")
[void]$sb.AppendLine('                <Fill color="#FF07090F" />')
[void]$sb.AppendLine('                <Stroke color="#FF1F2D42" width="1" />')
[void]$sb.AppendLine('            </Ellipse>')
[void]$sb.AppendLine('        </PartDraw>')

# Slot 1: minute counter (text = minutes, title = MIN ELAPSED / MIN LEFT from the phone's countMode)
[void]$sb.AppendLine('        <ComplicationSlot slotId="1" x="150" y="170" width="150" height="70" displayName="Minute counter" supportedTypes="SHORT_TEXT" isCustomizable="TRUE">')
[void]$sb.AppendLine('            <BoundingOval x="0" y="0" width="150" height="70" />')
[void]$sb.AppendLine('            <DefaultProviderPolicy primaryProvider="com.planner1440.app/com.planner1440.watchface.MinuteCounterComplicationService" primaryProviderType="SHORT_TEXT" defaultSystemProvider="STEP_COUNT" defaultSystemProviderType="SHORT_TEXT" />')
[void]$sb.AppendLine('            <Complication type="SHORT_TEXT">')
[void]$sb.AppendLine('                <PartText x="0" y="0" width="150" height="44">')
[void]$sb.AppendLine('                    <Text align="CENTER">')
[void]$sb.AppendLine('                        <Font family="SYNC_TO_DEVICE" size="36" weight="BOLD" color="#FFF59E0B">')
[void]$sb.AppendLine('                            <Template>%s<Parameter expression="[COMPLICATION.TEXT]" /></Template>')
[void]$sb.AppendLine('                        </Font>')
[void]$sb.AppendLine('                    </Text>')
[void]$sb.AppendLine('                </PartText>')
[void]$sb.AppendLine('                <PartText x="0" y="44" width="150" height="26">')
[void]$sb.AppendLine('                    <Text align="CENTER">')
[void]$sb.AppendLine('                        <Font family="SYNC_TO_DEVICE" size="13" color="#FF64748B">')
[void]$sb.AppendLine('                            <Template>%s<Parameter expression="[COMPLICATION.TITLE]" /></Template>')
[void]$sb.AppendLine('                        </Font>')
[void]$sb.AppendLine('                    </Text>')
[void]$sb.AppendLine('                </PartText>')
[void]$sb.AppendLine('            </Complication>')
[void]$sb.AppendLine('        </ComplicationSlot>')

# Clock time under the dial
[void]$sb.AppendLine('        <DigitalClock x="145" y="242" width="160" height="26">')
[void]$sb.AppendLine('            <TimeText format="h:mm" hourFormat="SYNC_TO_DEVICE" align="CENTER">')
[void]$sb.AppendLine('                <Font family="SYNC_TO_DEVICE" size="19" color="#FF94A3B8" />')
[void]$sb.AppendLine('            </TimeText>')
[void]$sb.AppendLine('        </DigitalClock>')

# Slot 2: next block (title + time from the phone snapshot)
[void]$sb.AppendLine('        <ComplicationSlot slotId="2" x="95" y="300" width="260" height="44" displayName="Next block" supportedTypes="SHORT_TEXT" isCustomizable="TRUE">')
[void]$sb.AppendLine('            <BoundingOval x="0" y="0" width="260" height="44" />')
[void]$sb.AppendLine('            <DefaultProviderPolicy primaryProvider="com.planner1440.app/com.planner1440.watchface.NextBlockComplicationService" primaryProviderType="SHORT_TEXT" defaultSystemProvider="DATE" defaultSystemProviderType="SHORT_TEXT" />')
[void]$sb.AppendLine('            <Complication type="SHORT_TEXT">')
[void]$sb.AppendLine('                <PartText x="0" y="0" width="260" height="44">')
[void]$sb.AppendLine('                    <Text align="CENTER" ellipsis="TRUE">')
[void]$sb.AppendLine('                        <Font family="SYNC_TO_DEVICE" size="20" color="#FFE2E8F0">')
[void]$sb.AppendLine('                            <Template>%s<Parameter expression="[COMPLICATION.TEXT]" /></Template>')
[void]$sb.AppendLine('                        </Font>')
[void]$sb.AppendLine('                    </Text>')
[void]$sb.AppendLine('                </PartText>')
[void]$sb.AppendLine('            </Complication>')
[void]$sb.AppendLine('        </ComplicationSlot>')

# Minute hand on the 1440 dial: a full-size group rotated about the face centre
$handLen = $r * 0.62
[void]$sb.AppendLine('        <Group x="0" y="0" width="450" height="450" pivotX="0.5" pivotY="0.5" angle="0">')
[void]$sb.AppendLine("            <Transform target=`"angle`" value=`"$dayAngle`" />")
[void]$sb.AppendLine('            <PartDraw x="0" y="0" width="450" height="450">')
[void]$sb.AppendLine("                <Line startX=`"$(F $cx)`" startY=`"$(F $cy)`" endX=`"$(F $cx)`" endY=`"$(F ($cy - $handLen))`">")
[void]$sb.AppendLine('                    <Stroke color="#FFF59E0B" width="2.2" cap="ROUND" />')
[void]$sb.AppendLine('                </Line>')
[void]$sb.AppendLine('            </PartDraw>')
[void]$sb.AppendLine('        </Group>')

# Centre dot
[void]$sb.AppendLine('        <PartDraw x="0" y="0" width="450" height="450">')
[void]$sb.AppendLine("            <Ellipse x=`"$(F ($cx - 3.5))`" y=`"$(F ($cy - 3.5))`" width=`"7`" height=`"7`">")
[void]$sb.AppendLine('                <Fill color="#FFF59E0B" />')
[void]$sb.AppendLine('            </Ellipse>')
[void]$sb.AppendLine('        </PartDraw>')

[void]$sb.AppendLine('    </Scene>')
[void]$sb.AppendLine('</WatchFace>')

$out = [System.IO.Path]::GetFullPath($out)
[System.IO.File]::WriteAllText($out, $sb.ToString(), (New-Object System.Text.UTF8Encoding $false))
Write-Output "wrote $out ($($sb.Length) chars)"
